package com.hibernate.D2;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

public class Main {

	public static void main(String[] args) {
		
		
	    //DML
         Employee employee= new Employee();
		
		//employee.setId(3); //autogeneratedvalue already assign in AUTO AND IT create new table in db to show the next increament  
         employee.setId(2);
         employee.setfName("Bella");
         employee.setlName("Getu");
         employee.setSalary(1000.00);
         employee.setDepartment("Angular");
         //employee.setNetTax(500);
		
		companyProfile companyProfile= new companyProfile();
		
		companyProfile.setComapanyname("Nike");
		companyProfile.setAddress("USA");
		companyProfile.setContactNum("123456789");
		companyProfile.setCeo("Enzoo");
		
		employee.setCompanyProfile(companyProfile);
		
		// Load xml to our application
				Configuration config= new Configuration(); // it comes from .cfg
				config.configure("hibernate.cfg.xml").addAnnotatedClass(Employee.class); // as parameter | java object 
				SessionFactory sessionFactory= config.buildSessionFactory(); // from .org | build xml and class
				Session session=sessionFactory.openSession();// from .org | open session  + connection ready 
				Transaction transaction=session.beginTransaction();
				////////////////////////////////////////////////////////
				
				//CREATE
				//session.save(employee); 
				 
				//SELECT
	            //System.out.print(session.get(Employee.class,3));

	            //UPDATE 
				//session.update(employee);
				
				//DELETE 
				//session.delete(employee);
	            
				/////////////////////////////////////////////////////////
				transaction.commit();
				session.close();

	}

}
